# 파이썬 기초 문법

## 1. 변수와 자료형

파이썬에서 변수는 데이터를 저장하는 공간입니다. 변수는 값을 할당할 때 자동으로 자료형을 결정합니다. 주요 자료형에는 정수(int), 실수 (float), 문자열 (str), 불리언(bool) 등이 있습니다.

`# 변수선언 및 대입 방법`
`변수명 = 값`

In [3]:
# 변수선언 및 대입
val = 5
# 변수값 출력
print(val, type(val), id(val))

5 <class 'int'> 140733372024056

In [4]:
# 연산 결과 변수에 저장
val = 5 + 7
# 변수값 출력
print(val)

12

In [5]:
# 변수값을 이용한 연산 값 저장
val1 = 12
val2 = 34
val3 = val1 + val2
print(val3)

46

## 2. 자료형
### 숫자형
* 정수(int): 소숫점이 없는 숫자. 1, -23, 0 등
* 실수(float): 소숫점이 있는 숫자. 3.14, -0.5, 12e11, 13E-4 등
* 8진수 : 0o123, 0O456
* 16진수: 0x78, 0x1A, 0X2F 등

In [6]:
# 숫자형 자료형 예제
val1 = 1
val2 = -23
val3 = 3.14
val4 = -0.5
val5 = 12e-6
val6 = 0.123e4
val7 = 0o456
val8 = 0x89A

print(val1, type(val1), id(val1))
print(val2, type(val2), id(val2))
print(val3, type(val3), id(val3))
print(val4, type(val4), id(val4))
print(val5, type(val5), id(val5))
print(val6, type(val6), id(val6))
print(val7, type(val7), id(val7))
print(val8, type(val8), id(val8))

1 <class 'int'> 140733372023928
-23 <class 'int'> 1522582235152
3.14 <class 'float'> 1522582238992
-0.5 <class 'float'> 1522573734384
1.2e-05 <class 'float'> 1522587025456
1230.0 <class 'float'> 1522587025488
302 <class 'int'> 1522582240560
2202 <class 'int'> 1522582235376

### 논리형

* 비교연산이나 논리연산의 결과를 표현하는 자료형
* 조건을 만족하면 참(True), 만족하지 않으면 거짓(False)으로 표현
* 반드시 첫 글자는 대문자로 작성해야 함

In [8]:
a = True
b = False
c = True

print(a, type(a), id(a))
print(b, type(b), id(b))
print(c, type(c), id(c))

True <class 'bool'> 140733371124480
False <class 'bool'> 140733371124512
True <class 'bool'> 140733371124480

### 산술연산자

* 숫자를 연산하는데 사용하는 연산 기호
* 더하기(+), 뺴기 (-), 곱하기(*), 나누기 (/)를 연산하는 사칙연산자
* 나눗셈의 몫(//)과 나머지(%)를 구하는 연산자
* 승수(거듭제곱)(**)을 구하는 연산자

In [9]:
a = 7
b = 3
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

10
4
21
2.3333333333333335
2
1
343

### 비교연산자
* 두 수의 크기를 비교하는 연산자
* 크다(>), 크거나 같다(>=), 작다(<), 작거나 같다(<=), 같다 (==), 같지 않다 (!=)
* 연산의 결과를 만족하면 참(True), 만족하지 않으면 거짓(False)으로 결과값을 반환

In [10]:
a = 3
b = 4

print(a > b)
print(a >= b)
print(a < b)
print(a <= b)
print(a == b)
print(a != b)

False
False
True
True
False
True

### 논리연산자

* 서로 다른 조건의 논리적 연산에 사용되는 연산자
* 연산자에는 and, or, not이  있음

In [1]:
# and 연산자
print(False and False)
print(False and True)
print(True and False)
print(True and True)

False
False
False
True

In [2]:
# or 연산자
print(False or False)
print(False or True)
print(True or False)
print(True or True)

False
True
True
True

In [1]:
# not 연산자
print(not True)
print(not False)

False
True

### 문자열 (str)

* 문자, 단어, 숫자, 특수문자 등으로 나열된 문자들의 집합
* 작은따옴표(') 혹은 큰따옴표(")로 감싸서 표현

In [3]:
# 문자열 지정
str1 = "I'm a student"
str2 = 'He say "Hi!"'

print(str1)
print(str2)

I'm a student
He say "Hi!"

In [6]:
str3 = '''My name is Yoo.
Nice to meet you.'''
str4 = """반갑습니다,
잘 부탁 드립니다."""

print(str3)
print(str4)

My name is Yoo.
Nice to meet you.
반갑습니다,
잘 부탁 드립니다.

In [9]:
# 이스케이프 문자열

str5 = 'I\'m a student'
str6 = "He say \"Hello\"." 

print(str5)
print(str6)

# 줄바꿈 (\n), 탭 (\t)

str7 = 'My name is Yoo. \nNice to meet you.'
str8 = "반갑습니다. \t잘 부탁 드립니다."

print(str7)
print(str8)

I'm a student
He say "Hello".
My name is Yoo.
Nice to meet you.
반갑습니다. 	잘 부탁 드립니다.

### 문자열 연산자

- (+) 연산자 : 문자열을 연결할 때 사용
- (*) 연산자 : 문자열을 반복할 때 사용

In [10]:
# + 연산자
str1 = "Python"
str2 = " is fun."
print(str1+str2)

Python is fun.

In [11]:
# * 연산자
print(str1 * 3)

PythonPythonPython

In [12]:
# * 연산자 응용
print('-' * 10)
print(str1)
print("-" * 10)

----------
Python
----------

In [14]:
# 문자열의 길이를 구하는 함수 : len()
str3 = "Life is too short."
print(len(str3))

18

In [15]:
print(str3)
print("-" * len(str3))

Life is too short.
------------------

In [16]:
# 문자열 인덱싱
print(str3[2])

f

In [19]:
# 문자열의 첫번째 글자
print(str3[0])
# 문자열의 마지막 글자
print(str3[len(str3)-1])
print(str3[-1])

L
.
.

### 문자열슬라이싱

* 인덱스 범위를 지정하여 추출하는 바법

'[인덱스시작번호 : 종료인덱스번호]

In [23]:
str3[8:11]
str3[-5]

'h'

In [24]:
# count 함수: 해당하는 문자열이 등장한 횟수
str3.count('o')

3

### 문자열 조작 함수

In [29]:
# count() 함수 : 해당하는 문자열이 등장한 횟수
print(str3)
str3.count('s')

Life is too short.

2

In [28]:
# index() 함수
str3.index('s')

6

In [34]:
# find() 함수: 해당하는 문자열의 처음 위치를 검색
print(str3)
str3.find('s')

Life is too short.

6

In [35]:
# 없는 문자는 -1 리턴
str3.find('x')

-1

In [42]:
# find 함수를 사용해서 두 번째 's'로 시작하는 5글자 단어 슬라이싱

str3[str3.find('s',str3.find('s')+1):str3.find('s',str3.find('s')+1)+5]

'short'

In [ ]:
str_slice = str3[str3.find('s')+1:]
str_slice[str_slice.find('s'):str_slice.find('s')+5]

'short'

### 문자열 포맷팅

- 포멧 문자열
    - %s : 문자열 대체
    - %d : 정수 대체
    - %f : 실수 대체
    - %o : 8진수 대체
    - %x : 16진수 대체
    - %% : % 기호 자체를 나타낼 때 사용

In [45]:
temp = 30
str = "오늘 날씨 온도는 %d도입니다." % temp
print(str)

오늘 날씨 온도는 30도입니다.

In [46]:
val = 35
print("10진수 %d는 8진수 %o, 16진수 %x 입니다." % (val, val, val))

10진수 35는 8진수 43, 16진수 23 입니다.

* format() 함수
    - 문자열 안에 중괄호({})를 사용하여 값을 대체
    - 중괄호 안에 인덱스 번호를 지정하여 순서를 바꿀 수 있음

In [49]:
str = "I eat {0} apples."
str.format(3)

'I eat 3 apples.'

In [52]:
str = "I eat {1} apple, so I was sick for {0} days."
str.format('some', 'a lot of')

'I eat a lot of apple, so I was sick for some days.'

* f문자열 포멧팅
    - f문자열 내에서 중괄호({})를 사용하여 변수 값을 직접 삽입

In [53]:
name = "너스트"
age = 26
f"내 이름은 {name} 입니다. 나이는 {age} 입니다"

'내 이름은 너스트 입니다. 나이는 26 입니다'

## 3. 제어문
 - 프로그램의 일부가 어떤 조건을 만족하는 경우에만 실행되도록 하거나, 특정 처리를 반복적으로 실행시킬 때 사용
 - 제어문에는 조건문(if문)과 반복문 (for문, while문) 이 있음

### 조건문 if
- 조건문은 특정 조건을 만족할 때만 실행되는 코드 블럭을 정의하는데 사용됩니다. 기본 구조는 다음과 같습니다.

```python
- if문 구조
if 조건식: 
    처리1
    처리2
elif 조건식:
    처리3
    처리4
else :
    처리5
    처리6
```

In [5]:
# 조건 분기가 하나인 경우
n = int(input())
if n % 2 == 0 :
    print("짝수")
else :
    print("홀수")
print("프로그램 종료")

짝수
프로그램 종료

In [6]:
# 조건 분기가 여러개인 경우
n = int(input("점수 : "))
if n > 90:
    print("A")
elif n>80:
    print("B")
elif n>70:
    print("C")
elif n>60:
    print("D")
else:
    print("F")

B

In [8]:
hei = float(input("키(cm) : "))
wei = float(input("체중(kg) : "))
bmi = wei * 10000 / hei / hei

print("BMI : %f" % bmi)
if bmi >= 35:
    print("비만 3단계")
elif bmi >= 30:
    print("비만 2단계")
elif bmi >= 25:
    print("비만 1단계")
elif bmi >= 18.5:
    print("정상")
else:
    print("저체중")

BMI : 25.216253
비만 1단계

In [ ]:
name = input("이름: ")
korean = int(input("국어 : "))
english = int(input("영어 : "))
math = int(input("수학 : "))
avg = (korean+english+math)/3

print("이름 : %s" % name)
print("국어 : %d 점" % korean)
print("영어 : %d 점" % english)
print("수학 : %d 점" % math)
print("총점 : %d 점" % (korean+english+math))
print("평균 : %f 점" % (avg))
if avg > 90:
    print("등급: A")
elif n>80:
    print("등급: B")
elif n>70:
    print("등급: C")
elif n>60:
    print("등급: D")
else:
    print("등급: F")

### While문 구조
while 조건식 :
    반복처리

In [12]:
# 반복조건을 제어하는 변수
n = 0
sum = 0
while n < 100:
    n = n+1
    sum = sum + n

print(sum)

5050

In [14]:
# 1~100 사이의 짝수의 갯수
num = 0
count = 0
while num < 100:
    num = num + 1
    if num % 2 == 0:
        count = count + 1

print(count)

50

- while 문 사용시 주의사항
1. 무한루프에 빠지지 않도록 조건문이 False가 되도록 반복문 내에서 조건을 변경해야 함
2. 반드시 반복을 탈출시킬 수 있는 탈출 조건을 만들어야 함
3. 경우에 따라서 무한루프를 만드는 경우, break 문을 사용해서 반복문을 종료해야 함
4. 반복중 일부분을 거넌뛰고 싶을 때는 continue문을 사용하여 다음 반복으로 넘어가도록 할 수 있음

In [ ]:
# 반복문 강제 종료

n = 0 
while True:
    n = n + 1
    print(n)
    if n == 10:
        break

print("프로그램 종료")

1
2
3
4
5
6
7
8
9
10
프로그램 종료

### 반복문 for
- for문은 시퀀스(리스트, 튜블, 문자열 등)의 각 요소를 순화하면서 반복적으로 실행되는 코드 블럭

``` #for문 구조
for 반복변수 in 시퀀스 : 
    반복처리```

In [25]:
# 문자열 길이만큼 반복

for char in "Life is too short.": 
    print(f"[{char}]")

[L]
[i]
[f]
[e]
[ ]
[i]
[s]
[ ]
[t]
[o]
[o]
[ ]
[s]
[h]
[o]
[r]
[t]
[.]

In [ ]:
sum = 0
for i in range(1,101):
    sum = sum + i
print(sum)

5050

### 제어문 중첩

In [36]:
# for문 중첩
for i in range(2,10):
    print("=== %d단 ===\n" % i)
    for j in range(2,10):
        print("%d * %d = %d" % (i, j, (i*j)))

=== 2단 ===

2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
=== 3단 ===

3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
=== 4단 ===

4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
=== 5단 ===

5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
=== 6단 ===

6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
=== 7단 ===

7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
=== 8단 ===

8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
=== 9단 ===

9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81

In [37]:
# print() 함수 사용시 자동 줄바꿈 없애는 방법
print("첫번째 출력")
print("2번째 출력", end='')
print("3번째 출력", end=' ')
print("4번째 출력", end='\t')
print("5번째 출력", end='.')

첫번째 출력
2번째 출력3번째 출력 4번째 출력	5번째 출력.

In [ ]:
# 옆으로 출력하는 구구단
for i in range(2,10):
    print("=== %d단 ===" % i, end='\t')

for j in range(1,10):
    print()
    for k in range(2,10):
        result = k*j
        print("%d * %d = %d" % (k, j, result), end='\t')

=== 2단 ===	=== 3단 ===	=== 4단 ===	=== 5단 ===	=== 6단 ===	=== 7단 ===	=== 8단 ===	=== 9단 ===
2 * 1 = 2	3 * 1 = 3	4 * 1 = 4	5 * 1 = 5	6 * 1 = 6	7 * 1 = 7	8 * 1 = 8	9 * 1 = 9
2 * 2 = 4	3 * 2 = 6	4 * 2 = 8	5 * 2 = 10	6 * 2 = 12	7 * 2 = 14	8 * 2 = 16	9 * 2 = 18
2 * 3 = 6	3 * 3 = 9	4 * 3 = 12	5 * 3 = 15	6 * 3 = 18	7 * 3 = 21	8 * 3 = 24	9 * 3 = 27
2 * 4 = 8	3 * 4 = 12	4 * 4 = 16	5 * 4 = 20	6 * 4 = 24	7 * 4 = 28	8 * 4 = 32	9 * 4 = 36
2 * 5 = 10	3 * 5 = 15	4 * 5 = 20	5 * 5 = 25	6 * 5 = 30	7 * 5 = 35	8 * 5 = 40	9 * 5 = 45
2 * 6 = 12	3 * 6 = 18	4 * 6 = 24	5 * 6 = 30	6 * 6 = 36	7 * 6 = 42	8 * 6 = 48	9 * 6 = 54
2 * 7 = 14	3 * 7 = 21	4 * 7 = 28	5 * 7 = 35	6 * 7 = 42	7 * 7 = 49	8 * 7 = 56	9 * 7 = 63
2 * 8 = 16	3 * 8 = 24	4 * 8 = 32	5 * 8 = 40	6 * 8 = 48	7 * 8 = 56	8 * 8 = 64	9 * 8 = 72
2 * 9 = 18	3 * 9 = 27	4 * 9 = 36	5 * 9 = 45	6 * 9 = 54	7 * 9 = 63	8 * 9 = 72	9 * 9 = 81

## 4. 리스트
- 여러개의 데이터를 하나의 집합으로 다루는 자료형
- 리스트는 대괄호([])로 감싸서 표현하며, 각 요소는 쉼표(,)로 구분
- 파이썬에서 사용하는 모든 자료형을 섞어서 사용 가능

In [7]:
# list 기본 사용법
li = [1,2,3,4,5]
print(li, type(li))

[1, 2, 3, 4, 5] <class 'list'>

In [58]:
# 하나의 자료에 다양한 
a = 10
b = 'Python'
c = True
d = 2.17
e = [1,2,3]

list1 = [a,b,c,d,e]

print(list1)

[10, 'Python', True, 2.17, [1, 2, 3]]

In [9]:
# 리스트 인덱싱
list1[1]

'Python'

In [13]:
# 다차원 인덱싱
list1[4][1]

2

In [11]:
# 리스트 슬라이싱
list1[:5]

[10, 'Python', True, 2.17, [1, 2, 3]]

In [14]:
# 리스트 크기 구하기
len(list1)

5

In [15]:
for el in list1: 
    print(el)

10
Python
True
2.17
[1, 2, 3]

In [59]:
list1[2] = False
list1

[10, 'Python', False, 2.17, [1, 2, 3]]

In [52]:
list1[0] + list1[3]

12.17

In [60]:
# 리스트 값 추가
list1.append(100)
list1

[10, 'Python', False, 2.17, [1, 2, 3], 100]

In [61]:
# 리스트 요소 중간에 추가
list1.insert(1, 'abcd')
list1

[10, 'abcd', 'Python', False, 2.17, [1, 2, 3], 100]

In [62]:
# 리스트 요소 삭제
del list1[1]
list1

[10, 'Python', False, 2.17, [1, 2, 3], 100]

In [63]:
# 리스트 값으로 삭제
list1.remove(False)
list1

[10, 'Python', 2.17, [1, 2, 3], 100]

## 5. 튜플
- 기존 구조는 리스트와 거의 유사
- 리스트와 달리 한 번 정의되면 요소를 변경, 추가, 삭제할 수 없는 구조형
- ()를 사용하여 원소를 정의하고 원소의 구분은 쉼표(,)를 사용

In [64]:
# 튜플 구조
tp1 = (1,2,3,4,5)
print(tp1, type(tp1))

(1, 2, 3, 4, 5) <class 'tuple'>

In [65]:
# 여러가지 자료형을 혼합해서 사용 가능
tp2 = (1, 2.3, 'abc', False, [4,5,6,7], (8,9,10))
tp2

(1, 2.3, 'abc', False, [4, 5, 6, 7], (8, 9, 10))

## 6. 딕셔너리(Dictionary)
- 키(key)와 값(value)을 한 쌍으로 갖는 자료형
- 중괄호({})를 사용하여 정의하고, 키와 값은 쌍으로 지정
- 키는 고유해야 하며, 값은 중복될 수 있음
- 키를 사용하여 값을 조회하거나 수정할 수 있음
- 저장되는 순서가 없음

In [66]:
# 딕셔너리 기본 사용
dic1 = {"name":"너스트", "age":48,"tel":"010-1234-5678"}

dic1

{'name': '너스트', 'age': 48, 'tel': '010-1234-5678'}

In [67]:
# 딕셔너리 인덱싱
dic1["name"]

'너스트'

In [68]:
# 딕셔너리 값 수정
dic1['age'] = 25
dic1

{'name': '너스트', 'age': 25, 'tel': '010-1234-5678'}

In [69]:
# 딕셔너리 요소 추가
dic1['addr'] = '포항시 남구'
dic1

{'name': '너스트', 'age': 25, 'tel': '010-1234-5678', 'addr': '포항시 남구'}

In [70]:
dic1['perso'] = 'bad'
dic1

{'name': '너스트',
 'age': 25,
 'tel': '010-1234-5678',
 'addr': '포항시 남구',
 'perso': 'bad'}

In [71]:
# 딕셔너리 요소 삭제
del dic1['perso']
dic1

{'name': '너스트', 'age': 25, 'tel': '010-1234-5678', 'addr': '포항시 남구'}

In [73]:
# 다중 인덱싱
dic2 = {"int":123, "float":4.56, "str":"abcdef", "list":[1,2,3,4,5],"tuple":(6,7,8,9), "dictionary":dic1}
dic2

{'int': 123,
 'float': 4.56,
 'str': 'abcdef',
 'list': [1, 2, 3, 4, 5],
 'tuple': (6, 7, 8, 9),
 'dictionary': {'name': '너스트',
  'age': 25,
  'tel': '010-1234-5678',
  'addr': '포항시 남구'}}

In [76]:
dic2['str'][2]

'c'

In [77]:
dic2['dictionary']['name']

'너스트'

In [ ]:
# 딕셔너리의 키값 추출
dic2.keys()

dict_keys(['int', 'float', 'str', 'list', 'tuple', 'dictionary'])

In [85]:
# 딕셔너리의 값 추출
dic2.values()

dict_values([123, 4.56, 'abcdef', [1, 2, 3, 4, 5], (6, 7, 8, 9), {'name': '너스트', 'age': 25, 'tel': '010-1234-5678', 'addr': '포항시 남구'}])

In [88]:
# 문제: for문을 사용해서 딕셔너리의 키와 값을 한줄씩 출력

for i in dic2:
    print(f"{i} : {dic2[i]}")

int : 123
float : 4.56
str : abcdef
list : [1, 2, 3, 4, 5]
tuple : (6, 7, 8, 9)
dictionary : {'name': '너스트', 'age': 25, 'tel': '010-1234-5678', 'addr': '포항시 남구'}

### 중간 문제
- 키보드로 입력 (이름, 국어, 영어, 수학)
- 입력받은 정보로 딕셔너리 생성
- 총점, 평균, 학점을 계산해서 딕셔너리에 추가
- 딕셔너리를 리스트에 추가
- 이름이 "q"가 입력되면 반복문 종료

In [ ]:
list3 = []
ranks = {'A':90, 'B':80, 'C':70, 'D':60}

while True:
    student = {'name':'홍길동','kor':99,'eng':88,'mat':77,'tot':0,'avg':0,'grade':'A'}
    student['name'] = input("학생 이름:")
    if student['name'] == 'q':
        break
    student['kor'] = int(input("국어 성적:"))
    student['eng'] = int(input("영어 성적:"))
    student['mat'] = int(input("수학 성적:"))
    student['tot'] = student['kor'] + student['eng'] + student['mat']
    student['avg'] = student['tot'] / 3
    for pending in ranks:
        if student['avg'] >= ranks[pending]:
            break
    student['grade'] = pending
    list3.append(student)

for student in list3:
    for key in student:
        print(f"{key} : {student[key]}")
    print()

name : A
kor : 70
eng : 80
mat : 90
tot : 240
avg : 80.0
grade : B
name : B
kor : 50
eng : 60
mat : 70
tot : 180
avg : 60.0
grade : D
name : C
kor : 90
eng : 95
mat : 100
tot : 285
avg : 95.0
grade : A

## 7. 집합 (set)
- 수학에서 집합을 연산하기 위한 자료형
- 중복을 허용하지 않음
- 순서가 없기 때문에 인덱싱으로 접근할 수 없음
- 집합은 중괄호 ({})를 사용하여 정의하며, 각 요소는 쉼표(,)로 구분

In [97]:
# 집합 구조
s1 = {1,2,3,4,5}
s2 = {4,5,6,7,8,7}

print(s1,s2)

{1, 2, 3, 4, 5} {4, 5, 6, 7, 8}

In [101]:
# 다른 자료형을 이용한 집합 생성
s3 = set("hello")
print(s3)

{'h', 'e', 'o', 'l'}

In [102]:
s4 = set([0,1,2,3,4,5,6,7,8])
print(s4)

{0, 1, 2, 3, 4, 5, 6, 7, 8}

In [104]:
# 집합의 연산 (합집합)

s1 | s2

{1, 2, 3, 4, 5, 6, 7, 8}

In [106]:
s1.union(s2)

{1, 2, 3, 4, 5, 6, 7, 8}

In [107]:
# 교집합 연산
s1 & s2

{4, 5}

## 8. 함수 (function)
- 특정 기능을 모듈화하여 필요시 호출하여 사용
- 사용자 정의 함수 : 사용자(프로그래머)가 직접 기능을 정의해서 사용하는 것
- 내장 함수 : 파이썬에서 기본적으로 제공하는 함수
- 람다 함수 : 간단한 처리를 인라인(한줄)으로 정의하여 사용, 복잡한 처리 불가능

### 사용자 정의 함수 

- 사용자가 직접 정의하여 호출하는 함수

```Python
# 함수 정의
def 함수명(매개변수):
    처리1
    처리2
    return 반환값
```

In [2]:
# 함수 정의 연습
def add(a, b):
    return a + b

add (2, 3)

5

In [4]:
# 매개변서(파라메타)가 없는 함수
def say():
    return 'Hi'

say()

'Hi'

In [5]:
# 변환값(리턴값) 없는 함수
def add(a, b):
    print(f"{a}와 {b}의 합은 {a+b}입니다.")

add(5,6)

5와 6의 합은 11입니다.

In [6]:
# 매개변수에 디폴트 값 설정
def cal(n1, n2, op='+'):
    if op == '+':
        return n1 + n2
    elif op == '-':
        return n1-n2
    elif op == '*':
        return n1*n2
    elif op == '/':
        return n1/n2

cal(1,2,'-')

-1

In [8]:
def sum(*args):
    result = 0
    for i in args :
        result = result + i
    return result

sum(1,2,3,4,5,6,7,8,9,5)

50

In [9]:
# 반환값이 여러개인 경우
def add_and_mul(a,b) :
    return a+b, a*b

add_result, mul_result = add_and_mul(7,8)
print(add_result,mul_result)

15 56

In [10]:
# 로컬변수(지역변수)와 글로벌변수(전역변수)
a = 1

def vartest(a):
    a = a + 1

vartest(a)
print(a)

1

In [12]:
# 글로벌(전역)변수 선언 방법
a = 1

def vartest():
    global a
    a = a + 1

vartest()
print(a)

2

In [ ]:
# 비밀번호 체크 코드를 함수화하여 변경

alphabet = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
number = set("1234567890")
special = set("!@#$%&*+-/")
def test(password):
    paset = set(password)
    if (len(password) >= 8
    and len(password) <= 16
    and len(paset & alphabet) > 0
    and len(paset & number) > 0
    and len(paset & special) > 0
    and len(paset & {' '}) == 0):
       return True
    return False

while True:
    new = input("새로운 비밀번호를 입력해주세요.")
    if test(new):
        break
    print("비밀번호 형식이 올바르지 않습니다.")
print("비밀번호가 설정되었습니다.")

비밀번호 형식이 올바르지 않습니다.
비밀번호 형식이 올바르지 않습니다.
비밀번호 형식이 올바르지 않습니다.
비밀번호 형식이 올바르지 않습니다.
비밀번호 형식이 올바르지 않습니다.
비밀번호가 설정되었습니다.

### 람다(lambda) 함수
- 람다 함수는 간단한 처리를 한 줄로 정의하여 사용할 수 있는 익명 함수입니다.
- 복잡한 처리는 붉능하며, 주로 간단한 연산이나 함수를 인자로 전다할 때 사용됩니다.

```Python
# 람다 함수 정의 방법
함수형 = lambda 매개변수1, 매개변서2, ... : 매개변수를 이용한 표현식
```

In [15]:
# lambda 함수 예제
add = lambda a, b : a + b

add(3,4)

7

In [16]:
def even_make(start, end):
    even_list = []
    for i in range(start, end+1):
        if i % 2 == 0:
            even_list.append(i)
    return even_list

even_make(1,10)

[2, 4, 6, 8, 10]

In [19]:
en_make = lambda start, end : [ i for i in range(start, end+1) if i % 2 == 0]
en_make(10,20)

[10, 12, 14, 16, 18, 20]

### 파이썬 내장 함수
- 파이썬에서 기본으로 제공하는 함수

In [1]:
nlist = [1,2,3,4,5,6,7,8,9]
sum(nlist)

45

In [2]:
# min(), max() 함수
print(min(nlist), max(nlist))

1 9

In [ ]:
# abs() 함수: 절대값 구하기
abs(-105)

105

In [4]:
# round() 함수: 반올림
round(3.1415, 2)

3.14

In [5]:
# divmod() 함수: 나눗셈, 몫과 나머지
divmod(29, 6)

(4, 5)

In [14]:
# int() 함수: 무조건 정수로 변환. 소숫점 버림, 두 번째 인자 부여시 진수 계산해서 10진수로 변환.
int(12.3456)

12

In [11]:
int('1010', 2)

10

In [15]:
# str(), list(), set(), dict()

In [ ]:
# enumerate() 함수: 리스트의 값에 번호(인덱스)를 붙여서 같이 꺼내주는 함수
for i, j in enumerate(nlist):
    print(i, j)

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9

In [17]:
# isdecimal() 함수: 숫자로만 이루어져있는가 판단. 문자, 소숫점, 마이너스도 숫자가 아님
"123".isdecimal()

True

In [18]:
#  isalpha() 함수: 영문자(혹은 문자)로만 이루어져있는가 판단
"abc".isalpha()

True

In [ ]:
# isascii() 함수: ASCII 문자로만 이루어져 있는가 (영어, 숫자, 특수문자. 한글/이모지는 X)
'abcd'.isascii()

True

## 9. 파일 입출력

### 파일 생성함수 open()

```python
# open() 함수 구조
파일객체명 = open(파일명(패스포함), 파일모드)
#파일닫기
파일객체명.close  
```

* 파일모드

파일모드 | 설명
:-----:|-----
r | 읽기모드, 파일이 존재하지 않으면 오류 발생
w | 쓰기모드, 파일이 존재하지 않으면 새로 생성, 존재하면 기존 내용 덮어쓰기
a | 추가모드, 파일이 존재하지 않으면 새로 생성, 존재하면 기존 내용 뒤에 추가

In [14]:
# 파일 쓰기 (w 모드)
f = open("test.txt", "w", encoding='utf-8')
for i in range(1,11):
    data = f'{i}번째 줄입니다.\n'
    f.write(data)
f.close()

In [15]:
# 파일 쓰기 (a 모드)
f = open("test.txt", "a", encoding='utf-8')
for i in range(1,11):
    data = f'{i}번째 줄입니다.\n'
    f.write(data)
f.close()

In [20]:
# 파일 읽기
f = open('test.txt', 'r', encoding='utf-8')
line = f.readline()
print(line)
f.close()

1번째 줄입니다.

In [24]:
# 파일의 전체 라인 읽어오기
f = open('test.txt', 'r', encoding='utf-8')

while True : 
    line = f.readline()
    if not line :
        break
    print(line)
f.close()

1번째 줄입니다.

2번째 줄입니다.

3번째 줄입니다.

4번째 줄입니다.

5번째 줄입니다.

6번째 줄입니다.

7번째 줄입니다.

8번째 줄입니다.

9번째 줄입니다.

10번째 줄입니다.

1번째 줄입니다.

2번째 줄입니다.

3번째 줄입니다.

4번째 줄입니다.

5번째 줄입니다.

6번째 줄입니다.

7번째 줄입니다.

8번째 줄입니다.

9번째 줄입니다.

10번째 줄입니다.

In [26]:
# 파일 읽기 시에 줄바꿈 제거해서 읽어오기

f = open('test.txt', 'r', encoding='utf-8')
lines = f.readlines()
print(lines)
for line in lines:
    line = line.strip()
    print(line)
f.close()

['1번째 줄입니다.\n', '2번째 줄입니다.\n', '3번째 줄입니다.\n', '4번째 줄입니다.\n', '5번째 줄입니다.\n', '6번째 줄입니다.\n', '7번째 줄입니다.\n', '8번째 줄입니다.\n', '9번째 줄입니다.\n', '10번째 줄입니다.\n', '1번째 줄입니다.\n', '2번째 줄입니다.\n', '3번째 줄입니다.\n', '4번째 줄입니다.\n', '5번째 줄입니다.\n', '6번째 줄입니다.\n', '7번째 줄입니다.\n', '8번째 줄입니다.\n', '9번째 줄입니다.\n', '10번째 줄입니다.\n']
1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.
1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.

In [28]:
# 파일 객체를 사용해서 읽어오기
f = open('test.txt', 'r', encoding='utf-8')
for line in f: 
    line = line.strip()
    print(line)
f.close()

1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.
1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.

### csv 파일

In [25]:
# csv 파일 읽어와서 저장하기

data_list = []

f = open("학생.csv", "r", encoding="utf-8")

for line in f.readlines():
    line = line.strip()
    data_record = line.split(',')
    print(data_record)

f.close()

['번호', '이름', '성별', '나이', '주소']
['1', '고길동', '남', '29', '서울']
['2', '나대로', '남', '25', '인천']
['3', '도인준', '남', '28', '부산']
['4', '라하니', '여', '24', '대구']
['5', '모순자', '여', '31', '포항']
['6', '박두리', '남', '27', '대전']
['7', '서영희', '여', '25', '전주']
['8', '이경희', '여', '30', '광주']
['9', '정수라', '여', '29', '춘천']
['10', '차범근', '남', '35', '제주']

In [ ]:
# with 문으로 파일 읽고 쓰기
with open('학생.csv', 'r', encoding = 'utf-8') as f:
    for line in f.readlines():
        line = line.strip()
        data_record = line.split(',')
        data_list.append(data_record)

print(data_list)

[['번호', ' 이름', ' 성별', ' 나이', ' 주소'], ['1', ' 고길동', ' 남', ' 29', ' 서울'], ['2', ' 홍길동', ' 남', ' 25', ' 부산'], ['3', ' 김예나', ' 여', ' 26', ' 수원'], ['4', ' 장현우', ' 남', ' 19', ' 서울'], ['5', ' 권수아', ' 여', ' 26', ' 화성'], ['6', ' 헤이즈', ' 여', ' 24', ' 대전'], ['7', ' 정하늘', ' 여', ' 28', ' 광주'], ['8', ' 도민준', ' 남', ' 27', ' 대구'], ['9. 구론희', ' 여', ' 29', ' 춘천'], ['10. 김춘식', ' 남', ' 23', ' 포항']]

In [26]:
# csv 패키지를 이용한 csv 파일 읽어오기
# csv 패키지 임포트
import csv

with open('학생.csv', 'r', encoding='utf-8') as f:
    data = csv.DictReader(f)
    for row in data: 
        print(row)

{'번호': '1', '이름': '고길동', '성별': '남', '나이': '29', '주소': '서울'}
{'번호': '2', '이름': '나대로', '성별': '남', '나이': '25', '주소': '인천'}
{'번호': '3', '이름': '도인준', '성별': '남', '나이': '28', '주소': '부산'}
{'번호': '4', '이름': '라하니', '성별': '여', '나이': '24', '주소': '대구'}
{'번호': '5', '이름': '모순자', '성별': '여', '나이': '31', '주소': '포항'}
{'번호': '6', '이름': '박두리', '성별': '남', '나이': '27', '주소': '대전'}
{'번호': '7', '이름': '서영희', '성별': '여', '나이': '25', '주소': '전주'}
{'번호': '8', '이름': '이경희', '성별': '여', '나이': '30', '주소': '광주'}
{'번호': '9', '이름': '정수라', '성별': '여', '나이': '29', '주소': '춘천'}
{'번호': '10', '이름': '차범근', '성별': '남', '나이': '35', '주소': '제주'}

In [24]:
# json 파일 읽어오기
import json

with open('test.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

print(data)

{'학생정보': [{'번호': '1', '이름': '고길동', '성별': '남', '나이': '29', '주소': '서울'}, {'번호': '2', '이름': '홍길동', '성별': '남', '나이': '25', '주소': '부산'}, {'번호': '3', '이름': '김예나', '성별': '여', '나이': '26', '주소': '수원'}, {'번호': '4', '이름': '장현우', '성별': '남', '나이': '19', '주소': '서울'}, {'번호': '5', '이름': '권수아', '성별': '여', '나이': '26', '주소': '화성'}, {'번호': '6', '이름': '헤이즈', '성별': '여', '나이': '24', '주소': '대전'}, {'번호': '7', '이름': '정하늘', '성별': '여', '나이': '28', '주소': '광주'}, {'번호': '8', '이름': '도민준', '성별': '남', '나이': '27', '주소': '대구'}, {'번호': '9', '이름': '구론희', '성별': '여', '나이': '29', '주소': '춘천'}, {'번호': '10', '이름': '김춘식', '성별': '남', '나이': '23', '주소': '포항'}]}

# 데이터 처리 모듈

## 1. numpy
- 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지
- 루프를 사용하지 않고 대량 데이터의 배열 연산이 가능
- 한가지 타입만 저장 가능
- 데이터분석, AI 분야 뿐만 아니라 자연과학, 공학에서도 널리 사용

In [1]:
# 모듈 설치
%pip install numpy

Requirement already satisfied: numpy in c:\Users\PC2510\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.5.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# numpy 임포트
import numpy as np
# numpy 버전 확인
np.__version__

'2.5.1'

In [4]:
# Numpy에서 사용하는 자료형: 배열(array)
array1 = np.array([1,2,3,4,5])
print(array1,type(array1))

[1 2 3 4 5] <class 'numpy.ndarray'>

In [5]:
# 2차원 배열
array2 = np.array([[1,2,3],[4,5,6]])
print(array2,type(array2))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>

In [6]:
# 3차원 배열
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(array3,type(array3))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]] <class 'numpy.ndarray'>

In [ ]:
# 배열 형태 확인 (면, 행, 열 순서)
print(array1.shape)
print(array2.shape)
print(array3.shape)

(5,)
(2, 3)
(2, 3, 3)

In [9]:
# 몇차원 배열인지 확인
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3

In [17]:
# 배열의 인덱싱과 슬라이싱
print(array1[0])
print(array2[1][1])
print(array2[1,0])

print(array3[0,1,2])

1
5
4
6

In [24]:
print(array1[1:3])

[2 3]

In [26]:
print(array2[0:2,1:3])

[[2 3]
 [5 6]]

In [28]:
array2[:,1:]

array([[2, 3],
       [5, 6]])

In [30]:
test_list = [[1,'아무개1','남','포항'],
             [2,'아무개2','남','포항'],
             [3,'아무개3','남','포항'],
             [4,'아무개4','남','포항'],
             [5,'아무개5','남','포항'],]

test_array = np.array(test_list)
print(test_array)

[['1' '아무개1' '남' '포항']
 ['2' '아무개2' '남' '포항']
 ['3' '아무개3' '남' '포항']
 ['4' '아무개4' '남' '포항']
 ['5' '아무개5' '남' '포항']]

In [31]:
test_array[:,:2]

array([['1', '아무개1'],
       ['2', '아무개2'],
       ['3', '아무개3'],
       ['4', '아무개4'],
       ['5', '아무개5']], dtype='<U21')

In [32]:
array4 = np.arange(10)
print(array4)

[0 1 2 3 4 5 6 7 8 9]

In [39]:
array4 = np.arange(1,25)
array5 = array4.reshape(-1,3,2)
print(array4)
print(array5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]

In [3]:
# 랜덤 데이터 만들기
arr1 = np.random.rand(6)
print(arr1)

[0.35504935 0.64957298 0.4660474  0.42519344 0.13574035 0.5537383 ]

In [121]:
# 시드값 설정
np.random.seed(810)
arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
print(arr1)
print(arr2)

[0.04478916 0.64186452 0.96159354 0.03997773 0.00464802 0.50531965
 0.70867694 0.91577292 0.12312106 0.7134329 ]
[0.46444634 0.40143491 0.23113091 0.10819891 0.30248283 0.06583042
 0.97292817 0.07452607 0.69888563 0.49172675]

### 통계 용어
- 분산: 중앙에서 얼마나 퍼저있는 정도
- 표준편차: 분산값이 너무 커서 직관적으로 보기 힘들기 때문에 분산에 루트를 씌워서 크기를 줄인 값
- 평균값: 데이터들의 평균
- 중앙값: 데이터를 작은것부터 큰것으로 나열을 해서, 정 중앙에 위치한 값
- 4분위: 데이터의 범위를 4구역으로 나눈 값(1/4분위(25%), 2/4분위(50%), 3/4분위(75%), 4/4분위(100%))

In [80]:
# 정규분포로 데이터 생성
# np.random.normal (loc = 중앙값, scale = 표준편차, size = 데이터수)
arr2 = np.random.normal(70, 15, 30)
print(arr2)

[32.71130542 82.93884289 68.0248633  71.47326512 71.99004729 65.96610579
 62.21114894 85.40961475 86.60492112 56.78828537 56.55546871 58.47780663
 65.22730474 40.84035852 90.13334151 80.88221175 56.8233599  73.99615716
 80.41381745 76.38374611 68.21405244 92.27481001 90.56451165 87.35076952
 65.84506585 83.70835688 77.61439426 36.40190979 78.85643181 70.84809687]

In [81]:
# 표준편차
print(f'표준편차 : {np.std(arr2)}')
# 중앙값
print(f'중앙값 : {np.median(arr2)}')
# 평균값
print(f'평균값 : {np.mean(arr2)}')
# 4분위값
print(f'1분위 : {np.percentile(arr2,25)}')
print(f'2분위 : {np.percentile(arr2,50)}')
print(f'3분위 : {np.percentile(arr2,75)}')
print(f'4분위 : {np.percentile(arr2,100)}')

표준편차 : 15.349398120518817
중앙값 : 71.73165620499064
평균값 : 70.51767905278695
1분위 : 62.96518788882579
2분위 : 71.73165620499064
3분위 : 82.42468510412712
4분위 : 92.27481001179092

## 2. pandas 패키지
- 데이터 셋을 다루는 패키지
- 1차원 배열(array) 형태는 시리즈(Series)
- 2차원 배열(array) 형태는 테이터프레임(DataFrame)

In [82]:
# pandas 설치
%pip install pandas

Requirement already satisfied: pandas in c:\Users\PC2510\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\PC2510\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\PC2510\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\PC2510\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\PC2510\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [85]:
# pandas 임포트
import pandas as pd
# 버전 확인
print(pd.__version__)

3.0.5

In [86]:
# Series 만들기
data1 = ['a','b','c','d','e','f']
s1 = pd.Series(data1)
print(type(s1),'\n',s1)

<class 'pandas.Series'>
 0    a
1    b
2    c
3    d
4    e
5    f
dtype: str

In [88]:
data2 = [1,2,3,4,5,6]
s2 = pd.Series(data2)
print(type(s2),'\n',s2)

<class 'pandas.Series'>
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [89]:
data3 = [0.1,2.3,4.5,6.7,8.9,10.0]
s3 = pd.Series(data3)
print(type(s3),'\n',s3)

<class 'pandas.Series'>
 0     0.1
1     2.3
2     4.5
3     6.7
4     8.9
5    10.0
dtype: float64

In [90]:
data4 = [True,False,True,False,True,False]
s4 = pd.Series(data4)
print(type(s4),'\n',s4)

<class 'pandas.Series'>
 0     True
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [92]:
data5 = [1,2.3,'4',True,5,6.7]
s5=pd.Series(data5)
print(type(s5),'\n',s5)

<class 'pandas.Series'>
 0       1
1     2.3
2       4
3    True
4       5
5     6.7
dtype: object

In [94]:
# 시리즈의 인덱싱 슬라이싱
s1.loc[0]

'a'

In [95]:
s2.loc[1:4]

1    2
2    3
3    4
4    5
dtype: int64

In [114]:
# 데이터 프레임 만들기

# for i in range(1,6)
dic1 = {'col1':s1,'col2':s2,'col3':s3,'col4':s4,'col5':s5,}
df1 = pd.DataFrame(dic1)
print(type(df1),'\n',df1)

<class 'pandas.DataFrame'>
   col1  col2  col3   col4  col5
0    a     1   0.1   True     1
1    b     2   2.3  False   2.3
2    c     3   4.5   True     4
3    d     4   6.7  False  True
4    e     5   8.9   True     5
5    f     6  10.0  False   6.7

In [108]:
# 1~4행, 열은 'col2'~'col4' 슬라이싱 하기
df1.loc[1:4,'col2':'col4']

   col2  col3   col4
1     2   2.3  False
2     3   4.5   True
3     4   6.7  False
4     5   8.9   True

In [116]:
# 데이터프레임의 인덱스명, 컬럼명 수정
df1.columns = ['알파벳','정수형','실수형','논리형','믹스']
df1

  알파벳  정수형   실수형    논리형    믹스
0   a    1   0.1   True     1
1   b    2   2.3  False   2.3
2   c    3   4.5   True     4
3   d    4   6.7  False  True
4   e    5   8.9   True     5
5   f    6  10.0  False   6.7

In [117]:
df1 = df1.rename(columns={df1.columns[1] : 'int'})
df1

  알파벳  int   실수형    논리형    믹스
0   a    1   0.1   True     1
1   b    2   2.3  False   2.3
2   c    3   4.5   True     4
3   d    4   6.7  False  True
4   e    5   8.9   True     5
5   f    6  10.0  False   6.7

In [118]:
df1.index

RangeIndex(start=0, stop=6, step=1)

In [119]:
df1.index = ['r1','r2','r3','r4','r5','r6']
df1

   알파벳  int   실수형    논리형    믹스
r1   a    1   0.1   True     1
r2   b    2   2.3  False   2.3
r3   c    3   4.5   True     4
r4   d    4   6.7  False  True
r5   e    5   8.9   True     5
r6   f    6  10.0  False   6.7